### ISSUE TITLE
GeoCode in Census location but not in Census demog acs

### ISSUE THREAD

**Issue by ewmoses** [kpwhri/vdw_census_sas_toolkit#2]
I ran the macro and as I was reviewing the results, I found some GeoCodes in my cemsus_location file that were not in the census_demog_acs file.  I went to census.gov and put in one of the addresses for GeoCode 27139081302.  The results were indeed that GeoCode.  Is it expected that there are GeoCodes in census_location that are  not in the census_demog_acs files?

This is the response that I received from Al:  
The geocoding app you're using is set to using the Census 2020 mapfiles. I could tell by eyeballing it was a split tract.... Here's how:
 
Let's start with the tract
27139081302
 
So… Here's how I read it:
1.	State = 27 (MN)
2.	County = 139 (Scott)
3.	Tract = 081302 This 02 indicates that tract 0813 split into at least two tracts (01 and 02)
 
If you set the vintage indicator to 2010, you'll get a different result:
27139081300
 
From the Census https://www.census.gov/programs-surveys/geography/about/glossary.html:
The Census Bureau uses suffixes to help identify census tract changes for comparison purposes. Census tract suffixes may range from .01 to .98. As part of local review of existing census tracts before each census, some census tracts may have grown enough in population size to qualify as more than one census tract. When a census tract is split, the split parts usually retain the basic number but receive different suffixes. For example, if census tract 14 is split, the new tract numbers would be 14.01 and 14.02. In a few counties, local participants request major changes to, and renumbering of, the census tracts; however, this is generally discouraged. Changes to individual census tract boundaries usually do not result in census tract numbering changes.
 
Currently released ACS files are only through 2019, all of which use the Census map vintage of 2010. So… when we have a 2020 split tract… we need to be using a 2020 ACS (not released yet). If you want to use the 2010-2019 ACS files, you need to be using 2010 vintage geocodes. 2020 vintage geocodes should only be used on 2020-2029 ACS releases.
 
If you were on the call today… This is the elaboration on the macro I was talking about. The future state of VDW will likely require both 2010 and 2020 vintage geocodes for some years in which a person might have a MRN+LOC_START.

**Comment by alphonsederus2** [comment]
Thank you for adding the issue! 

It also raises the concern that Census Location needs to include only the decade of the boundary year.

I think what we'll end up doing is adding an assessment step that rounds to the nearest tens place to assure the match in loc is pointing to the correct year in demog:
```
%macro round_tens(in_number);
	floor(&in_number/10)*10;
%mend round_tens;
```

**Comment by alphonsederus2** [comment]
GEOCODE_BOUNDARY_YEAR is being added to the CENSUS_DEMOG_ACS. This kind of obviates the need for further development.
